/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BecomeHostRouteImport } from './routes/become-host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as HostsSlugRouteImport } from './routes/hosts.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as DashboardModerationRouteImport } from './routes/dashboard.moderation'
import { Route as DashboardMembersRouteImport } from './routes/dashboard.members'
import { Route as HostsSlugEditRouteImport } from './routes/hosts.$slug.edit'
import { Route as EventsIdCheckInRouteImport } from './routes/events.$id.check-in'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard.events.new'
import { Route as DashboardEventsIdRouteImport } from './routes/dashboard.events.$id'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeHostRoute = BecomeHostRouteImport.update({
  id: '/become-host',
  path: '/become-host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardModerationRoute = DashboardModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRoute,
} as any)
const HostsSlugEditRoute = HostsSlugEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => HostsSlugRoute,
} as any)
const EventsIdCheckInRoute = EventsIdCheckInRouteImport.update({
  id: '/events/$id/check-in',
  path: '/events/$id/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdRoute = DashboardEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/moderation': typeof DashboardModerationRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hosts/$slug': typeof HostsSlugRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/check-in': typeof EventsIdCheckInRoute
  '/hosts/$slug/edit': typeof HostsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/moderation': typeof DashboardModerationRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hosts/$slug': typeof HostsSlugRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/check-in': typeof EventsIdCheckInRoute
  '/hosts/$slug/edit': typeof HostsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/tickets': typeof TicketsRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/moderation': typeof DashboardModerationRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hosts/$slug': typeof HostsSlugRouteWithChildren
  '/join/$token': typeof JoinTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/$id': typeof DashboardEventsIdRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/check-in': typeof EventsIdCheckInRoute
  '/hosts/$slug/edit': typeof HostsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-host'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/tickets'
    | '/dashboard/members'
    | '/dashboard/moderation'
    | '/events/$slug'
    | '/hosts/$slug'
    | '/join/$token'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/events/$id/check-in'
    | '/hosts/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-host'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/tickets'
    | '/dashboard/members'
    | '/dashboard/moderation'
    | '/events/$slug'
    | '/hosts/$slug'
    | '/join/$token'
    | '/dashboard'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/events/$id/check-in'
    | '/hosts/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/become-host'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/tickets'
    | '/dashboard/members'
    | '/dashboard/moderation'
    | '/events/$slug'
    | '/hosts/$slug'
    | '/join/$token'
    | '/dashboard/'
    | '/dashboard/events/$id'
    | '/dashboard/events/new'
    | '/events/$id/check-in'
    | '/hosts/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeHostRoute: typeof BecomeHostRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  TicketsRoute: typeof TicketsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  HostsSlugRoute: typeof HostsSlugRouteWithChildren
  JoinTokenRoute: typeof JoinTokenRoute
  EventsIdCheckInRoute: typeof EventsIdCheckInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-host': {
      id: '/become-host'
      path: '/become-host'
      fullPath: '/become-host'
      preLoaderRoute: typeof BecomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/moderation': {
      id: '/dashboard/moderation'
      path: '/moderation'
      fullPath: '/dashboard/moderation'
      preLoaderRoute: typeof DashboardModerationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/hosts/$slug/edit': {
      id: '/hosts/$slug/edit'
      path: '/edit'
      fullPath: '/hosts/$slug/edit'
      preLoaderRoute: typeof HostsSlugEditRouteImport
      parentRoute: typeof HostsSlugRoute
    }
    '/events/$id/check-in': {
      id: '/events/$id/check-in'
      path: '/events/$id/check-in'
      fullPath: '/events/$id/check-in'
      preLoaderRoute: typeof EventsIdCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id': {
      id: '/dashboard/events/$id'
      path: '/events/$id'
      fullPath: '/dashboard/events/$id'
      preLoaderRoute: typeof DashboardEventsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardModerationRoute: typeof DashboardModerationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsIdRoute: typeof DashboardEventsIdRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardModerationRoute: DashboardModerationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsIdRoute: DashboardEventsIdRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface HostsSlugRouteChildren {
  HostsSlugEditRoute: typeof HostsSlugEditRoute
}

const HostsSlugRouteChildren: HostsSlugRouteChildren = {
  HostsSlugEditRoute: HostsSlugEditRoute,
}

const HostsSlugRouteWithChildren = HostsSlugRoute._addFileChildren(
  HostsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeHostRoute: BecomeHostRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  TicketsRoute: TicketsRoute,
  EventsSlugRoute: EventsSlugRoute,
  HostsSlugRoute: HostsSlugRouteWithChildren,
  JoinTokenRoute: JoinTokenRoute,
  EventsIdCheckInRoute: EventsIdCheckInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
